# ========================================
# Jekyll 블로그 설정
# ========================================

# 사이트 정보
title: AI Quality Lab
tagline: AI-Powered QA Engineering
description: AI 기반 QA 자동화와 테스트 품질 관리에 대한 실무 경험과 기술 트렌드를 공유합니다.
url: https://junghyunryu.github.io
baseurl: /my-blog

# 테마
theme: minima

# 사용자 정보
author:
  name: 류정현
  email: jhryu115@gmail.com

# 소셜 미디어
minima:
  social_links:
    - { platform: email, user_url: "jhryu115@gmail.com" }
    - { platform: github, user_url: "https://github.com/junghyunryu" }

# 언어 및 시간대
lang: ko-KR
timezone: Asia/Seoul

# 플러그인
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-paginate

# 페이지 설정
paginate: 10
paginate_path: /page:num/

# 아카이브 설정
jekyll-archives:
  enabled:
    - categories
    # - tags  # 태그 아카이브 비활성화
  layouts:
    category: archive-category
    tag: archive-tag
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

# Markdown 설정
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: plaintext

# Minima 테마 설정
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/junghyunryu" }
  custom_css:
    - /assets/css/custom.css

# 제외할 파일/디렉토리
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - venv/
  - automation/
  - geeknews/
  - scripts/
  - tests/
  - deploy/
  - data/
  - run_geeknews.bat
  - run_geeknews.ps1
  - scheduler.py
  - requirements.txt
  - topics.json
  - Makefile
  - nohup.out

# 포함할 파일
include:
  - _pages
